allowCrossWorld: false
hearDistance: 50
cactusEnabled: true
drowningEnabled: true
fallEnabled: true
fireEnabled: true
lavaEnabled: true
lightningEnabled: true
mobEnabled: true
poisonEnabled: true
pvpEnabled: true
starvationEnabled: true
suffocationEnabled: true
suicideEnabled: true
tntEnabled: true
voidEnabled: true
defaultEnabled: true
customEnabled: true
