name: DeathMessages
version: 1.1.0
main: com.leetzilantonis.deathmessage.Main
commands:
  dmreload:
    description: reloads the death messages config and lang files
    aliases: [dmr]
    permission: deathmessages.reload
    usage: Something went wrong, You shouldnt be seeing this AT ALL!
permissions:
  deathmessages.*:
    description: Allows players to have all death message permissions
    default: op
    children:
      deathmessages.hear: true
      deathmessages.reload: true
  deathmessages.reload:
    description: Allows players to reload the config and lang file
    default: op
  deathmessages.hear:
    description: Allows players to hear or see death messages in chat
    default: true
